import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Ручная конфигурация — без автогенерации (sidebars: {autogenerated: ...}).
 * Категории с `link: {type: 'doc'}` указывают на индексную страницу раздела.
 */
const sidebars: SidebarsConfig = {
  egiszSidebar: [
    'egisz/index',
    {
      type: 'category',
      label: 'Подключение интеграции',
      items: [
        'egisz/connection/connection-process',
        'egisz/connection/technical-requirements',
        'egisz/connection/test-integration',
      ],
    },
    {
      type: 'category',
      label: 'Настройка',
      link: {type: 'doc', id: 'egisz/settings/index'},
      items: [
        'egisz/settings/organization',
        'egisz/settings/departments',
        'egisz/settings/employees',
        'egisz/settings/patient-data',
        'egisz/settings/integration-parameters',
        'egisz/settings/nsi',
        'egisz/settings/remd',
        'egisz/settings/iemk',
        'egisz/settings/replication',
        'egisz/settings/filials',
      ],
    },
    {
      type: 'category',
      label: 'Эксплуатация',
      link: {type: 'doc', id: 'egisz/operation/index'},
      items: [
        'egisz/operation/statuses',
        'egisz/operation/resend',
        'egisz/operation/patient-refusal',
        'egisz/operation/data-maintenance',
        'egisz/operation/faq',
      ],
    },
    {
      type: 'category',
      label: 'Диагностика',
      link: {type: 'doc', id: 'egisz/diagnostics/index'},
      items: [
        'egisz/diagnostics/check-list',
        'egisz/diagnostics/sql-configuration-check',
        'egisz/diagnostics/error-catalog',
        'egisz/diagnostics/support-request',
      ],
    },
    {
      type: 'category',
      label: 'СЭМД',
      link: {type: 'doc', id: 'egisz/semd/index'},
      items: [
        'egisz/semd/connection',
        'egisz/semd/profiles',
        'egisz/semd/protocol-configuration',
        'egisz/semd/catalog',
      ],
    },
    'egisz/remd-iemk',
    'egisz/terminology',
    'egisz/normative-bases',
    {
      type: 'category',
      label: 'Справочные материалы о других интеграциях',
      link: {type: 'doc', id: 'egisz/other-integrations/index'},
      items: [
        'egisz/other-integrations/foms',
        'egisz/other-integrations/netrika-spb',
        'egisz/other-integrations/snils-enrichment',
      ],
    },
  ],

  servicesSidebar: [
    'services1/index',
    {
      type: 'category',
      label: 'Система обновлений',
      link: {type: 'doc', id: 'services1/cp-upgrader/index'},
      items: [
        'services1/cp-upgrader/basic',
        'services1/cp-upgrader/pro',
        'services1/cp-upgrader/user',
        'services1/cp-upgrader/check',
      ],
    },
    {
      type: 'category',
      label: 'Система репликации',
      link: {type: 'doc', id: 'services1/replic/index'},
      items: [
        'services1/replic/setup',
        'services1/replic/configuration',
        'services1/replic/check',
      ],
    },
    {
      type: 'category',
      label: 'Модуль «Менеджер Загрузок»',
      link: {type: 'doc', id: 'sync_manager/index'},
      items: [
        'sync_manager/settings',
        'sync_manager/synchronization',
        'sync_manager/automation',
        'sync_manager/reference',
        'sync_manager/check',
      ],
    },
  ],

  podderzhkaSidebar: ['podderzhka/index'],
};

export default sidebars;
